// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriPlan.Data;

#nullable disable

namespace NutriPlan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315090302_AgregarPlanElegido")]
    partial class AgregarPlanElegido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NutriPlan.Models.ListaCompra", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLista"));

                    b.Property<bool>("Comprado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLista");

                    b.ToTable("lista_compra");
                });

            modelBuilder.Entity("NutriPlan.Models.Objetivo", b =>
                {
                    b.Property<int>("IdObjetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdObjetivo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdObjetivo");

                    b.ToTable("objetivos");
                });

            modelBuilder.Entity("NutriPlan.Models.PlanComida", b =>
                {
                    b.Property<int>("IdPlanComida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlanComida"));

                    b.Property<int>("IdPlanSemanal")
                        .HasColumnType("int");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<string>("MomentoDia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPlanComida");

                    b.ToTable("plan_comida");
                });

            modelBuilder.Entity("NutriPlan.Models.PlanSemanal", b =>
                {
                    b.Property<int>("IdPlanSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlanSemanal"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPlanSemanal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("plan_semanal");
                });

            modelBuilder.Entity("NutriPlan.Models.Receta", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReceta"));

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdReceta");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("NutriPlan.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdObjetivo")
                        .HasColumnType("int");

                    b.Property<string>("PlanElegido")
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdObjetivo");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("NutriPlan.Models.PlanSemanal", b =>
                {
                    b.HasOne("NutriPlan.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NutriPlan.Models.Usuario", b =>
                {
                    b.HasOne("NutriPlan.Models.Objetivo", null)
                        .WithMany()
                        .HasForeignKey("IdObjetivo");
                });
#pragma warning restore 612, 618
        }
    }
}
